<?php

if (!function_exists('admin_copy')) {
    function admin_copy(string $key, ?string $fallback = null): string
    {
        static $copy = [
            'admin.general.success' => 'Success!',
            'admin.general.error' => 'Error',
            'admin.general.save' => 'Save',
            'admin.general.cancel' => 'Cancel',
            'admin.general.delete' => 'Delete',
            'admin.general.edit' => 'Edit',
            'admin.general.add' => 'Add',
            'admin.general.actions' => 'Actions',
            'admin.general.search_placeholder' => 'Search...',
            'admin.general.id' => 'ID',
            'admin.general.name' => 'Name',
            'admin.general.price' => 'Price',
            'admin.general.description' => 'Description',
            'admin.general.back' => 'Back',
            'admin.general.administrator' => 'Administrator',
            'admin.general.logout' => 'Logout',
            'admin.general.dashboard' => 'Dashboard',
            'admin.general.users' => 'Users',
            'admin.general.roles' => 'Roles',
            'admin.general.role' => 'Role',
            'admin.general.permissions' => 'Permissions',
            'admin.general.copyright' => '© 2026 CRUD Admin System',
            'admin.general.powered_by' => 'Powered by TanpaNgoding',

            'admin.login.title' => 'Login | CRUD Admin',
            'admin.login.welcome' => 'Welcome Back',
            'admin.login.subtitle' => 'Please sign in to your account',
            'admin.login.email_label' => 'Email Address',
            'admin.login.email_placeholder' => 'admin@example.com',
            'admin.login.password_label' => 'Password',
            'admin.login.password_placeholder' => 'Your password',
            'admin.login.signin_button' => 'Sign In',
            'admin.login.signin_google' => 'Sign in with Google',
            'admin.login.secure_access' => 'Secure Administrator Access',

            'admin.dashboard.title' => 'System Overview',
            'admin.dashboard.subtitle' => "Welcome back, here's what's happening today.",
            'admin.dashboard.revenue' => 'Total Revenue',
            'admin.dashboard.users' => 'Active Users',
            'admin.dashboard.orders' => 'Total Orders',
            'admin.dashboard.conversion' => 'Conversion Rate',
            'admin.dashboard.live_data' => 'Live Dummy Data',
            'admin.dashboard.last_sync' => 'Updated 5 minutes ago',
            'admin.dashboard.performance_title' => 'Revenue Trend',
            'admin.dashboard.performance_subtitle' => 'Gross revenue and orders over the last seven months.',
            'admin.dashboard.traffic_title' => 'Traffic Sources',
            'admin.dashboard.traffic_subtitle' => 'Acquisition split across your strongest channels.',
            'admin.dashboard.direct_channel' => 'Direct',
            'admin.dashboard.social_channel' => 'Social',
            'admin.dashboard.marketplace_channel' => 'Marketplace',
            'admin.dashboard.email_channel' => 'Email',
            'admin.dashboard.sales_mix_title' => 'Sales by Category',
            'admin.dashboard.sales_mix_subtitle' => 'Dummy order volume by category for the current quarter.',
            'admin.dashboard.pipeline_title' => 'Regional Pipeline',
            'admin.dashboard.pipeline_subtitle' => 'Pipeline readiness by sales region.',
            'admin.dashboard.goal_completion' => 'Goal Completion',
            'admin.dashboard.goal_subtitle' => 'Monthly target completion based on current trajectory.',
            'admin.dashboard.top_channels_title' => 'Top Channels',
            'admin.dashboard.top_channels_subtitle' => 'Best-performing channels from this week.',
            'admin.dashboard.top_channels_badge' => 'Top 4',
            'admin.dashboard.activity_title' => 'Recent Activity',
            'admin.dashboard.activity_subtitle' => 'Operational updates captured in the last few hours.',
            'admin.dashboard.activity_badge' => 'Live Feed',

            'admin.profile.title' => 'Admin Profile',
            'admin.profile.subtitle' => 'Manage your account information and password.',
            'admin.profile.update_success' => 'Profile updated successfully.',
            'admin.profile.password_mismatch' => 'The current password does not match.',
            'admin.profile.basic_info' => 'Basic Information',
            'admin.profile.change_password' => 'Change Password',
            'admin.profile.current_password' => 'Current Password',
            'admin.profile.new_password' => 'New Password',
            'admin.profile.confirm_password' => 'Confirm New Password',
            'admin.profile.password_placeholder' => 'Leave blank if you do not want to change',
            'admin.profile.password_min_hint' => 'Minimum 6 characters',
            'admin.profile.save_button' => 'Save Changes',

            'admin.users.management' => 'User Management',
            'admin.users.subtitle' => 'Manage administrator accounts and their assigned roles.',
            'admin.users.add_new' => 'Add User',
            'admin.users.add_user' => 'Add User',
            'admin.users.edit_user' => 'Edit User',
            'admin.users.add_subtitle' => 'Create a new admin user and assign a role.',
            'admin.users.edit_subtitle' => 'Update user details and assigned role.',
            'admin.users.email' => 'Email',
            'admin.users.role_placeholder' => 'Select a role',
            'admin.users.password_label' => 'Password',
            'admin.users.password_required' => 'Enter a password',
            'admin.users.password_optional' => 'Leave blank to keep current password',
            'admin.users.password_confirmation_label' => 'Confirm Password',
            'admin.users.no_role' => 'No role',
            'admin.users.empty_state' => 'No users found.',
            'admin.users.create_success' => 'User created successfully.',
            'admin.users.update_success' => 'User updated successfully.',
            'admin.users.delete_success' => 'User deleted successfully.',
            'admin.users.cannot_delete_last_super_admin' => 'The last super-admin user cannot be deleted.',
            'admin.users.cannot_remove_last_super_admin' => 'The last super-admin role cannot be removed from this account.',
            'admin.users.delete_confirm_title' => 'Delete this user?',
            'admin.users.delete_confirm_text' => 'This account will be permanently removed.',
            'admin.users.delete_confirm_yes' => 'Yes, delete',
            'admin.users.delete_confirm_no' => 'Cancel',

            'admin.roles.management' => 'Role Management',
            'admin.roles.subtitle' => 'Configure access levels and granular permissions.',
            'admin.roles.add_new' => 'Add Role',
            'admin.roles.add_role' => 'Add Role',
            'admin.roles.edit_role' => 'Edit Role',
            'admin.roles.add_subtitle' => 'Create a new role and choose its permissions.',
            'admin.roles.edit_subtitle' => 'Update the role name and permissions.',
            'admin.roles.name_placeholder' => 'e.g. manager',
            'admin.roles.permissions_help' => 'Choose the permissions available to this role. Dashboard access is always included.',
            'admin.roles.required_permission_hint' => 'Required',
            'admin.roles.system_role_badge' => 'System',
            'admin.roles.system_role_notice' => 'The super-admin role is a protected system role and cannot be modified from the UI.',
            'admin.roles.system_role_immutable' => 'The super-admin role cannot be modified.',
            'admin.roles.cannot_delete_system_role' => 'The super-admin role cannot be deleted.',
            'admin.roles.empty_state' => 'No roles found.',
            'admin.roles.create_success' => 'Role created successfully.',
            'admin.roles.update_success' => 'Role updated successfully.',
            'admin.roles.delete_success' => 'Role deleted successfully.',
            'admin.roles.delete_confirm_title' => 'Delete this role?',
            'admin.roles.delete_confirm_text' => 'Users assigned to this role will lose its access permissions.',
            'admin.roles.delete_confirm_yes' => 'Yes, delete',
            'admin.roles.delete_confirm_no' => 'Cancel',

            'admin.rbac.modules.dashboard' => 'Dashboard',
            'admin.rbac.modules.users' => 'Users',
            'admin.rbac.modules.roles' => 'Roles',
            'admin.rbac.permissions.dashboard_view' => 'View dashboard',
            'admin.rbac.permissions.users_view' => 'View users',
            'admin.rbac.permissions.users_create' => 'Create users',
            'admin.rbac.permissions.users_update' => 'Update users',
            'admin.rbac.permissions.users_delete' => 'Delete users',
            'admin.rbac.permissions.roles_view' => 'View roles',
            'admin.rbac.permissions.roles_create' => 'Create roles',
            'admin.rbac.permissions.roles_update' => 'Update roles',
            'admin.rbac.permissions.roles_delete' => 'Delete roles',
        ];

        if (isset($copy[$key])) {
            return $copy[$key];
        }
        if ($fallback !== null && $fallback !== '') {
            return $fallback;
        }

        $segments = explode('.', $key);
        $last = end($segments) ?: $key;
        $humanized = str_replace(['_', '-'], ' ', $last);
        $humanized = preg_replace('/\s+/', ' ', $humanized);

        return ucwords(trim($humanized));
    }
}
